// 古诗词库 — 用于背景随机展示
module.exports = [
  // ── 唐诗 ──
  { text: '大漠孤烟直，长河落日圆。', author: '王维', source: '使至塞上' },
  { text: '举头望明月，低头思故乡。', author: '李白', source: '静夜思' },
  { text: '海内存知己，天涯若比邻。', author: '王勃', source: '送杜少府之任蜀州' },
  { text: '天生我材必有用，千金散尽还复来。', author: '李白', source: '将进酒' },
  { text: '长风破浪会有时，直挂云帆济沧海。', author: '李白', source: '行路难' },
  { text: '会当凌绝顶，一览众山小。', author: '杜甫', source: '望岳' },
  { text: '无边落木萧萧下，不尽长江滚滚来。', author: '杜甫', source: '登高' },
  { text: '两个黄鹂鸣翠柳，一行白鹭上青天。', author: '杜甫', source: '绝句' },
  { text: '千山鸟飞绝，万径人踪灭。', author: '柳宗元', source: '江雪' },
  { text: '同是天涯沦落人，相逢何必曾相识。', author: '白居易', source: '琵琶行' },
  { text: '回眸一笑百媚生，六宫粉黛无颜色。', author: '白居易', source: '长恨歌' },
  { text: '春蚕到死丝方尽，蜡炬成灰泪始干。', author: '李商隐', source: '无题' },
  { text: '身无彩凤双飞翼，心有灵犀一点通。', author: '李商隐', source: '无题' },
  { text: '夕阳无限好，只是近黄昏。', author: '李商隐', source: '乐游原' },
  { text: '独在异乡为异客，每逢佳节倍思亲。', author: '王维', source: '九月九日忆山东兄弟' },
  { text: '行到水穷处，坐看云起时。', author: '王维', source: '终南别业' },
  { text: '空山新雨后，天气晚来秋。', author: '王维', source: '山居秋暝' },
  { text: '劝君更尽一杯酒，西出阳关无故人。', author: '王维', source: '渭城曲' },
  { text: '桃花潭水深千尺，不及汪伦送我情。', author: '李白', source: '赠汪伦' },
  { text: '抽刀断水水更流，举杯消愁愁更愁。', author: '李白', source: '宣州谢朓楼饯别' },
  { text: '安能摧眉折腰事权贵，使我不得开心颜。', author: '李白', source: '梦游天姥吟留别' },
  { text: '今人不见古时月，今月曾经照古人。', author: '李白', source: '把酒问月' },
  { text: '春风得意马蹄疾，一日看尽长安花。', author: '孟郊', source: '登科后' },
  { text: '沉舟侧畔千帆过，病树前头万木春。', author: '刘禹锡', source: '酬乐天扬州初逢' },
  { text: '旧时王谢堂前燕，飞入寻常百姓家。', author: '刘禹锡', source: '乌衣巷' },
  { text: '不知细叶谁裁出，二月春风似剪刀。', author: '贺知章', source: '咏柳' },
  { text: '黄河远上白云间，一片孤城万仞山。', author: '王之涣', source: '凉州词' },
  { text: '欲穷千里目，更上一层楼。', author: '王之涣', source: '登鹳雀楼' },
  { text: '但使龙城飞将在，不教胡马度阴山。', author: '王昌龄', source: '出塞' },
  { text: '洛阳亲友如相问，一片冰心在玉壶。', author: '王昌龄', source: '芙蓉楼送辛渐' },
  { text: '莫愁前路无知己，天下谁人不识君。', author: '高适', source: '别董大' },
  { text: '黑云压城城欲摧，甲光向日金鳞开。', author: '李贺', source: '雁门太守行' },
  { text: '男儿何不带吴钩，收取关山五十州。', author: '李贺', source: '南园' },
  { text: '曾经沧海难为水，除却巫山不是云。', author: '元稹', source: '离思' },
  { text: '此情可待成追忆，只是当时已惘然。', author: '李商隐', source: '锦瑟' },
  { text: '相见时难别亦难，东风无力百花残。', author: '李商隐', source: '无题' },
  { text: '商女不知亡国恨，隔江犹唱后庭花。', author: '杜牧', source: '泊秦淮' },
  { text: '停车坐爱枫林晚，霜叶红于二月花。', author: '杜牧', source: '山行' },
  { text: '清明时节雨纷纷，路上行人欲断魂。', author: '杜牧', source: '清明' },
  { text: '南朝四百八十寺，多少楼台烟雨中。', author: '杜牧', source: '江南春' },

  // ── 宋词 ──
  { text: '大江东去，浪淘尽，千古风流人物。', author: '苏轼', source: '念奴娇·赤壁怀古' },
  { text: '但愿人长久，千里共婵娟。', author: '苏轼', source: '水调歌头' },
  { text: '竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。', author: '苏轼', source: '定风波' },
  { text: '人间有味是清欢。', author: '苏轼', source: '浣溪沙' },
  { text: '十年生死两茫茫，不思量，自难忘。', author: '苏轼', source: '江城子' },
  { text: '人生如逆旅，我亦是行人。', author: '苏轼', source: '临江仙' },
  { text: '寻寻觅觅，冷冷清清，凄凄惨惨戚戚。', author: '李清照', source: '声声慢' },
  { text: '此情无计可消除，才下眉头，却上心头。', author: '李清照', source: '一剪梅' },
  { text: '生当作人杰，死亦为鬼雄。', author: '李清照', source: '夏日绝句' },
  { text: '知否，知否？应是绿肥红瘦。', author: '李清照', source: '如梦令' },
  { text: '众里寻他千百度，蓦然回首，那人却在，灯火阑珊处。', author: '辛弃疾', source: '青玉案' },
  { text: '醉里挑灯看剑，梦回吹角连营。', author: '辛弃疾', source: '破阵子' },
  { text: '想当年，金戈铁马，气吞万里如虎。', author: '辛弃疾', source: '永遇乐·京口北固亭怀古' },
  { text: '青山遮不住，毕竟东流去。', author: '辛弃疾', source: '菩萨蛮' },
  { text: '昨夜西风凋碧树，独上高楼，望尽天涯路。', author: '晏殊', source: '蝶恋花' },
  { text: '无可奈何花落去，似曾相识燕归来。', author: '晏殊', source: '浣溪沙' },
  { text: '落花人独立，微雨燕双飞。', author: '晏几道', source: '临江仙' },
  { text: '两情若是久长时，又岂在朝朝暮暮。', author: '秦观', source: '鹊桥仙' },
  { text: '纤云弄巧，飞星传恨，银汉迢迢暗度。', author: '秦观', source: '鹊桥仙' },
  { text: '问君能有几多愁？恰似一江春水向东流。', author: '李煜', source: '虞美人' },
  { text: '春花秋月何时了？往事知多少。', author: '李煜', source: '虞美人' },
  { text: '剪不断，理还乱，是离愁。别是一般滋味在心头。', author: '李煜', source: '相见欢' },
  { text: '林花谢了春红，太匆匆。', author: '李煜', source: '相见欢' },
  { text: '怒发冲冠，凭栏处、潇潇雨歇。', author: '岳飞', source: '满江红' },
  { text: '三十功名尘与土，八千里路云和月。', author: '岳飞', source: '满江红' },
  { text: '零落成泥碾作尘，只有香如故。', author: '陆游', source: '卜算子·咏梅' },
  { text: '山重水复疑无路，柳暗花明又一村。', author: '陆游', source: '游山西村' },
  { text: '王师北定中原日，家祭无忘告乃翁。', author: '陆游', source: '示儿' },
  { text: '小楼一夜听春雨，深巷明朝卖杏花。', author: '陆游', source: '临安春雨初霁' },
  { text: '人生自古谁无死？留取丹心照汗青。', author: '文天祥', source: '过零丁洋' },
  { text: '先天下之忧而忧，后天下之乐而乐。', author: '范仲淹', source: '岳阳楼记' },
  { text: '碧云天，黄叶地，秋色连波，波上寒烟翠。', author: '范仲淹', source: '苏幕遮' },
  { text: '衣带渐宽终不悔，为伊消得人憔悴。', author: '柳永', source: '蝶恋花' },
  { text: '多情自古伤离别，更那堪，冷落清秋节。', author: '柳永', source: '雨霖铃' },
  { text: '今宵酒醒何处？杨柳岸，晓风残月。', author: '柳永', source: '雨霖铃' },
  { text: '出淤泥而不染，濯清涟而不妖。', author: '周敦颐', source: '爱莲说' },

  // ── 先秦 ──
  { text: '路漫漫其修远兮，吾将上下而求索。', author: '屈原', source: '离骚' },
  { text: '长太息以掩涕兮，哀民生之多艰。', author: '屈原', source: '离骚' },
  { text: '亦余心之所善兮，虽九死其犹未悔。', author: '屈原', source: '离骚' },
  { text: '逝者如斯夫，不舍昼夜。', author: '孔子', source: '论语' },
  { text: '三人行，必有我师焉。', author: '孔子', source: '论语' },
  { text: '己所不欲，勿施于人。', author: '孔子', source: '论语' },
  { text: '学而不思则罔，思而不学则殆。', author: '孔子', source: '论语' },
  { text: '知之者不如好之者，好之者不如乐之者。', author: '孔子', source: '论语' },
  { text: '天地与我并生，而万物与我为一。', author: '庄子', source: '齐物论' },
  { text: '子非鱼，安知鱼之乐？', author: '庄子', source: '秋水' },
  { text: '相濡以沫，不如相忘于江湖。', author: '庄子', source: '大宗师' },
  { text: '上善若水，水善利万物而不争。', author: '老子', source: '道德经' },
  { text: '千里之行，始于足下。', author: '老子', source: '道德经' },
  { text: '知人者智，自知者明。', author: '老子', source: '道德经' },
  { text: '天行健，君子以自强不息。', author: '周易', source: '易经' },
  { text: '穷则独善其身，达则兼济天下。', author: '孟子', source: '孟子' },

  // ── 元曲 / 明清 ──
  { text: '枯藤老树昏鸦，小桥流水人家，古道西风瘦马。', author: '马致远', source: '天净沙·秋思' },
  { text: '夕阳西下，断肠人在天涯。', author: '马致远', source: '天净沙·秋思' },
  { text: '兴，百姓苦；亡，百姓苦。', author: '张养浩', source: '山坡羊·潼关怀古' },
  { text: '滚滚长江东逝水，浪花淘尽英雄。', author: '杨慎', source: '临江仙' },
  { text: '是非成败转头空，青山依旧在，几度夕阳红。', author: '杨慎', source: '临江仙' },
  { text: '落红不是无情物，化作春泥更护花。', author: '龚自珍', source: '己亥杂诗' },
  { text: '我劝天公重抖擞，不拘一格降人才。', author: '龚自珍', source: '己亥杂诗' },
  { text: '苟利国家生死以，岂因祸福避趋之。', author: '林则徐', source: '赴戍登程口占示家人' },

  // ── 近代 ──
  { text: '数风流人物，还看今朝。', author: '毛泽东', source: '沁园春·雪' },
  { text: '恰同学少年，风华正茂；书生意气，挥斥方遒。', author: '毛泽东', source: '沁园春·长沙' },
  { text: '雄关漫道真如铁，而今迈步从头越。', author: '毛泽东', source: '忆秦娥·娄山关' },
];
